---
- name: Configuration des interfaces du CSR1000
  hosts: CSR1000
  gather_facts: no

  tasks:
    - name: Interfaces et descriptions
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: Interface WAN - DHCP
            enabled: true

          - name: GigabitEthernet2
            description: LAN Entreprise
            enabled: true

          - name: GigabitEthernet3
            description: LAN DMZ
            enabled: true

          - name: GigabitEthernet4
            description: LAN ADMIN
            enabled: true
        state: merged

    - name: IP des interfaces
      cisco.ios.ios_l3_interfaces:
        config:
          - name: GigabitEthernet1
            ipv4:
              - dhcp:
                  enable: true

          - name: GigabitEthernet2
            ipv4:
              - address: 192.168.2.1/24

          - name: GigabitEthernet3
            ipv4:
              - address: 192.168.3.1/24

          - name: GigabitEthernet4
            ipv4:
              - address: 192.168.4.1/24
        state: merged

    - name: Supprimer le pool DHCP s'il existe déjà
      cisco.ios.ios_config:
        lines:
          - no ip dhcp pool LAN_ENTREPRISE

    - name: Exclure l'adresse de l'interface
      cisco.ios.ios_config:
        lines:
          - ip dhcp excluded-address 192.168.2.1

    - name: Configurer le serveur DHCP pour LAN_ENTREPRISE
      cisco.ios.ios_config:
        parents: ip dhcp pool LAN_ENTREPRISE
        lines:
          - network 192.168.2.0 255.255.255.0
          - default-router 192.168.2.1
          - dns-server 8.8.8.8